apiVersion: v1
kind: Pod
metadata:
  name: cloud-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    component: cloud-controller-manager
spec:
  priorityClassName: system-node-critical
  hostNetwork: true
  containers:
    - name: cloud-controller-manager
      image: "mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.23.3"
      imagePullPolicy: IfNotPresent
      env:
      - name: AZURE_ENVIRONMENT_FILEPATH
        value: /etc/kubernetes/azurestackcloud.json
      - name: AZURE_GO_SDK_LOG_LEVEL
        value: INFO
      command: ["cloud-controller-manager"]
      args:
        - "--allocate-node-cidrs={{not IsAzureCNI}}"
        - "--cloud-config=/etc/kubernetes/azure.json"
        - "--cloud-provider=azure"
        - "--cluster-cidr={{PodCIDR}}"
        - "--cluster-name={{ClusterName}}"
        - "--configure-cloud-routes={{not IsAzureCNI}}"
        - "--controllers=*,-cloud-node"
        - "--kubeconfig=/etc/kubernetes/admin.conf"
        - "--leader-elect=true"
        - "--route-reconciliation-period=10s"
        - "--v=2"
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 4
          memory: 2Gi
      volumeMounts:
      - name: etc-kubernetes
        mountPath: /etc/kubernetes
      - name: etc-ssl
        mountPath: /etc/ssl
        readOnly: true
      - name: var-lib-kubelet
        mountPath: /var/lib/kubelet
      - name: msi
        mountPath: /var/lib/waagent/ManagedIdentity-Settings
        readOnly: true
  volumes:
    - name: etc-kubernetes
      hostPath:
        path: /etc/kubernetes
    - name: etc-ssl
      hostPath:
        path: /etc/ssl
    - name: var-lib-kubelet
      hostPath:
        path: /var/lib/kubelet
    - name: msi
      hostPath:
        path: /var/lib/waagent/ManagedIdentity-Settings
